### ISSUE TITLE
GU 16.45 - Death Trooper typos

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#100]
Quest Fixes
	Corrected Typos in Death Trooper Camp Delta Defense Quests

**Comment by ladybogit** [comment]
all NPC's are all currantly named "Undead Attacker" i tested all 4 points and 4 missons at all points

**Comment by Cekis** [comment]
The NPC's are likely not the issue.  The Camp Delta defense quests might have typo's in them though.

**Comment by ladybogit** [comment]
looks good but here is a screen shot of the npc converation for your aproval as i am dislecix
![image](https://user-images.githubusercontent.com/353448/113356908-91e0aa80-9332-11eb-8d6c-42fd5ec5fe39.png)
Edit the player inter actions look good
![image](https://user-images.githubusercontent.com/353448/113357352-65795e00-9333-11eb-91c8-80ea3475254c.png)

**Comment by Cekis** [comment]
Do you have a screen shot of the Quest Log and Quest Details?

**Comment by ladybogit** [comment]
as requested 
![image](https://user-images.githubusercontent.com/353448/113357553-b1c49e00-9333-11eb-8c2e-4704d6e778e3.png)

**Comment by ladybogit** [comment]
as discused on discord here are the rest of the camps
Alfa
![image](https://user-images.githubusercontent.com/353448/113358712-d4f04d00-9335-11eb-97d0-76179f72cd21.png)
bata
![image](https://user-images.githubusercontent.com/353448/113359348-1c2b0d80-9337-11eb-91a5-cd2b8dc0269b.png)
gamma
![image](https://user-images.githubusercontent.com/353448/113359943-51842b00-9338-11eb-81de-2d86b894fa92.png)
Epsalon
![image](https://user-images.githubusercontent.com/353448/113360509-74630f00-9339-11eb-931a-8887eda76fa5.png)

**Comment by Cekis** [comment]
That third one almost threw me (Gamma)... but he's alien so probably intentional.  I'm going to close this.
