### ISSUE TITLE
GU 16.45 - Heroic Loot

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#116]
Heroic
	23 new heroic decorative loot drops added to Axkva Min, Exar Kun, IG-88, Tusken Invasion, and Star Destroyer instances.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131266965-fccf58a6-4bae-461d-b39f-c4685256ab71.png)
![image](https://user-images.githubusercontent.com/89060381/131266979-6315e420-0811-4a5f-98c4-16e1ba9c39e4.png)

Currently drop.
