### ISSUE TITLE
GU 16.8 - Costume Icons

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#123]
Costumes
	All costumes have had their icons changed to reflect the creature or NPC they represent.

**Comment by ladybogit** [comment]
all tested working and displaying the correct icon the the exception of Vader due to a [bug](https://github.com/SWG-Source/dsrc/issues/200) i will update when it gets fixed

**Comment by langelusse** [comment]
I confirm bug with vador costume. I can't swear
