### ISSUE TITLE
GU 16.8 - ITV Deeds

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#146]
Misc
	You can no longer consume ITV deeds for an ITV command that you already have.

**Comment by Cigaran** [comment]
I generated two each of the following ITV deeds:

- Rattletrap (item_junk_itv)
- Corellian G9 Rigger Freighter (item_tcg_loot_reward_series4_location_itv_02_01)
- Geonosian Solar Sailer (item_tcg_loot_reward_series4_home_itv_02_01)

I used the Radial Menu on the deed, selected option 3 'Grant Ability', and was granted the new ability as expected.  Attempting to grant the ability a second time gave the system message "You have already used this item."
