### ISSUE TITLE
GU 16.0 - Dancing

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#173]
Misc
	Start/stop/change dances no longer display menus of options to players that do not issue the command.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131426969-4db8c3eb-c281-4c0b-bb27-eb62a86fc20e.png)
non issuer
![image](https://user-images.githubusercontent.com/89060381/131427028-227030e7-195b-4f9e-a970-7185a3f9fcff.png)
issuer
OK.

**Comment by langelusse** [comment]
Ok for me I closed
