### ISSUE TITLE
GU 17.0 - Storyteller - Tusken Raider Combat NPC Placement

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#213]
Storyteller		
	- Due to technical issues, the Tusken Raider Combat NPC Storyteller item may no longer be placed inside or on the roof/balcony of player structures.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131266826-66b8cc72-467c-4b10-b224-d0882316b88d.png)
OK.
