### ISSUE TITLE
GU 16.8 - Jedi - Heroic Jewelry

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#33]
Jedi
	The Guardian Set buff will now give a bonus to critical hit reduction (up to 5% for 5 pieces).

**Comment by ladybogit** [comment]
yes it is 5% CHR
![image](https://user-images.githubusercontent.com/353448/99673716-09412c00-2a6d-11eb-8b28-7d2e65fd858d.png)
![image](https://user-images.githubusercontent.com/353448/99673883-3261bc80-2a6d-11eb-9e7b-58dc878cb54b.png)
