### ISSUE TITLE
GU 16.8 - Jedi - Heroic Jewelry (#2)

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#34]
Jedi
	The Guardian set will now give +1 glancing blow per piece in place of the Block Chance.

**Comment by ladybogit** [comment]
it is glancing blow and it is +1 pre piece
![image](https://user-images.githubusercontent.com/353448/99674147-8ff60900-2a6d-11eb-8d23-f96ee918372c.png)
