### ISSUE TITLE
GU 16.8 - Jedi - Meditation Buff

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#35]
Jedi
	The Block chance and Block Value on the meditation buff 'Visions of the Past' has been changed to 3% Evasion Chance and 30% Evasion Value.

**Comment by ladybogit** [comment]
the values are stated above with 3% Evasion Chance and 30% Evasion Value.
![image](https://user-images.githubusercontent.com/353448/99674671-48bc4800-2a6e-11eb-956f-98a5936b99d9.png)
