### ISSUE TITLE
GU 17.1 - AT-ST/XT Two Seats

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#375]
Empire Day VII / Remembrance Day VII
	- The AT-XT and AT-ST are now both two-seaters. They also run a little faster.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131423933-d3bffbb4-c053-47ba-8e86-2a8edfa17965.png)
![image](https://user-images.githubusercontent.com/89060381/131424064-74159575-37f5-4f04-a827-6c5c4ebddacf.png)

Uncertain about the speed, but both are two-seaters.
