### ISSUE TITLE
GU 18.1 - Crafting - Weapon Deconstruction

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#419]
Weapon Crafting
	- Fixed the BWDL19 and the Jinkins J-1 Rifles so they can be correctly deconstructed and recrafted.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131266376-a3159c48-5a86-4bb0-ad0b-ca4f78cf4e75.png)
![image](https://user-images.githubusercontent.com/89060381/131266407-f1e89d61-9391-4025-aa90-c620d6f92f39.png)
OK.
