### ISSUE TITLE
GU 16.6 - Pfilbee Jhorn NPC clothing

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#46]
Misc
	The fashion police have re-educated another offender. Pfilbee Jhorn near Bestine will only wear a single set of clothes from now on.

**Comment by AuroraNGE** [comment]
it seems correct except that he is bald.
[https://zupimages.net/up/21/32/cmiq.jpg](url)

Compare at:

[](https://swg.fandom.com/wiki/Pfilbee_Jhorn)
