### ISSUE TITLE
Test Game Update 16.10 - Jabba's Sail Barge Deed Purchase

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#5]
ESB 30 - Week 4
	The Heroic Token Vendor in Aurillia now sells the Jabba's Sail Barge structure deed.

**Comment by ladybogit** [comment]
confirmed its there 
![image](https://user-images.githubusercontent.com/353448/99575120-1bb95800-29d0-11eb-89c6-d5ae355a4bb1.png)
