### ISSUE TITLE
GU 20.1 - Jedi - Meditation

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#715]
Jedi
	- Jedi Meditation now grants a 2% resource quality bonus.

**Comment by ladybogit** [comment]
confirmed
i have tested with crafting it bring a saver to 99% quality up form 97% with current ressore spawns on my TC 
![image](https://user-images.githubusercontent.com/353448/104032094-92e7bd00-51c5-11eb-8385-e47305045dfb.png)
