### ISSUE TITLE
GU 16.5 - Lok Water Table

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#77]
Plate Tectonics
	The planet wide thermostat for Lok has been lowered to address the rising temperature that is causing a rise in water level on Lok.
	Special load-bearing NPCs have been placed at strategic locations throughout Lok to address the issue of sinking ground on Lok. If you encounter these NPCs during your travels through Lok, please do not kill them or otherwise distract them from their duties, or Lok may become a huge sinkhole.

**Comment by langelusse** [comment]
No worries about the trn level that would make the water be above the ground in the plain for me it is solved.

**Comment by AconiteX** [comment]
I'm fine with closing this. I can't find anything anywhere about why this was implemented and I'm still not sure whether it was a joke or they were fixing something that SOE didn't specify in the patch notes. So unless Lok starts flooding, we'll call this one done.
