### ISSUE TITLE
GU 16.45 - Nitra Vendallan clothing

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#78]
Misc
	Nitra Vendallan in the Anchorhead cantina now only wears only one set of clothes.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131272214-83467ab0-4044-4f57-9823-5503f412d130.png)
OK.

**Comment by langelusse** [comment]
Ok for me
https://cdn.discordapp.com/attachments/875152096427647006/884805440553246802/unknown.png
