### ISSUE TITLE
GU 16.45 - Tyrena Starport Tombstone

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#80]
Misc
	Bad Spawner gravestone in Tyrena Starport removed

**Comment by langelusse** [comment]
I confirm

**Comment by Cekis** [comment]
Confirm it's NOT there or confirm it IS there?

**Comment by Cekis** [comment]
Giving the issue a qa-approved tag suggests that it is NOT there.

**Comment by langelusse** [comment]
We have no tombstone so it’s fixed for me
