### ISSUE TITLE
GU 16.45 - Droids, Pets and Destroying Structures

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#91]
Misc
	Structures can no longer be destroyed if the player has a callable droid or pet in the structure with them.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131271580-a35e8f0c-a050-40b9-a756-061bff408f67.png)
![image](https://user-images.githubusercontent.com/89060381/131271622-3949406a-0fcf-45b0-ab29-8464c7a12cd5.png)
OK.
