### ISSUE TITLE
GU 16.45 - Borvo Quest

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#94]
Quest Fixes
	Borvo the Hutt should no longer allow the player to bug themselves into never being able to complete his quests.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131272781-7cff9a52-f5f4-4ae7-8269-ec1c6a2ad883.png)
![image](https://user-images.githubusercontent.com/89060381/131272797-2c845b9a-409f-4493-8d98-04fd3f57cb8a.png)

Need more info.
![image](https://user-images.githubusercontent.com/89060381/131273069-a6aba42a-80f8-4cc6-8488-0670770f3087.png)

**Comment by langelusse** [comment]
https://swg.fandom.com/wiki/Borvo_the_Hutt_questline

**Comment by AconiteX** [comment]
The issue this was supposed to address is that if you deconstruct or destroy the Tusken rifle he gives you to take back to Darklighter's Estate, he should give you a new one to replace it with.

Meaning, if he gives you the rifle, and you destroy it, and talk to him again, he should give you another. 

Good? I can't tell from the screenshots.

**Comment by Cekis** [comment]
@langelusse can you respond or test this again?

**Comment by langelusse** [comment]
Work for me it's fixed
