### ISSUE TITLE
GU 16.45 - Ephant Mon Buff

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/qa-testing#98]
Quest Fixes
	Ephant Mon no longer rewards player with Terrain Negotiation click buff object. The reward is now a Stamina buff. Any existing Terrain Negotiation buffs should auto change with this update.

**Comment by BubbaJoeX** [comment]
![image](https://user-images.githubusercontent.com/89060381/131273816-5909c0e8-d757-4167-bc80-cf1ff15b5894.png)
OK.

**Comment by langelusse** [comment]
I confirm
